################
### 3conv3fc ###
################

debugvgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True --net_type "3conv3fc"
debugrand:
	python refactor_main_Bayes2.py --cv_type "rand" --debug True --net_type "3conv3fc"
vgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" --net_type "3conv3fc" # default debug False
rand:
	python refactor_main_Bayes2.py --cv_type "rand" --net_type "3conv3fc" # default --debug False

fdebugrand:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --debug True --net_type "3conv3fc" # default --debug False

fdebugvgmm:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --debug True --net_type "3conv3fc" # default --debug False


frand:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --net_type "3conv3fc"   # default --debug False

fvgmm:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --net_type "3conv3fc"  # default --debug False


###############
### AlexNet ###
###############

debugvgmm_alexnet:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True --net_type "alexnet"

debugrand_alexnet:
	python refactor_main_Bayes2.py --cv_type "rand" --debug True --net_type "alexnet"

vgmm_alexnet:
	python refactor_main_Bayes2.py --cv_type "vgmm" --net_type "alexnet" # default debug False

rand_alexnet:
	python refactor_main_Bayes2.py --cv_type "rand" --net_type "alexnet" # default --debug False

fdebugrand_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --debug True --net_type "alexnet" # default --debug False

fdebugvgmm_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --debug True --net_type "alexnet" # default --debug False

frand_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --net_type "alexnet"  # default --debug False

fvgmm_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --net_type "alexnet"  # default --debug False

#############
### LeNet ###
#############

debugvgmm_lenet:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True --net_type "lenet"

debugrand_lenet:
	python refactor_main_Bayes2.py --cv_type "rand" --debug True --net_type "lenet"

vgmm_lenet:
	python refactor_main_Bayes2.py --cv_type "vgmm" --net_type "lenet" # default debug False

rand_lenet:
	python refactor_main_Bayes2.py --cv_type "rand" --net_type "lenet" # default --debug False

fdebugrand_lenet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --debug True --net_type "lenet" # default --debug False

fdebugvgmm_lenet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --debug True --net_type "lenet" # default --debug False

frand_lenet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --net_type "lenet"  # default --debug False

fvgmm_lenet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --net_type "lenet"  # default --debug False
