debugvgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True
debugrand:
	python refactor_main_Bayes2.py --cv_type "rand" --debug True
vgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" # default debug False
rand:
	python refactor_main_Bayes2.py --cv_type "rand" # default --debug False

fdebugrand:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --debug True # default --debug False

fdebugvgmm:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --debug True # default --debug False


frand_3conv3fc:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --net_type "3conv3fc"  # default --debug False

fvgmm_3conv3fc:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --net_type "3conv3fc"  # default --debug False

frand_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "rand" --net_type "3conv3fc"  # default --debug False

fvgmm_alexnet:  # frequenst
	python refactor_main_Frequentist.py --cv_type "vgmm" --net_type "3conv3fc"  # default --debug False



debugvgmm_alexnet:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True --net_type "alexnet"

