debugvgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" --debug True
debugrand:
	python refactor_main_Bayes2.py --cv_type "rand" --debug True
vgmm:
	python refactor_main_Bayes2.py --cv_type "vgmm" # default debug False
rand:
	python refactor_main_Bayes2.py --cv_type "rand" # default --debug False
