rst_dir = '/home/sunxd/project/paper_2019_vgmm_vae_cv'
data_path = 'results/VAE_FashionMNIST_64_10'
result_path = 'results/VAE_FashionMNIST_64_10'
statistic_name4d_t = "/L-1/TSNE_transformed_data_dict.npy"
statistic_name4d_s = "/TSNE_transformed_data_dict.npy"
num_clusters=3
num_labels=10
dataset_name='FashionMNIST'
global_index_name='/global_index_cluster_data.npy'
TSNE_data_name='/TSNE_transformed_data_dict.npy'
cluster_index_json_name='/cluster_dict.json'
cluster_predict_tsv_name='/cluster_predict.tsv'
cluster_predict_npy_name='/cluster_predict.npy'
z_name='/z.npy'
y_name='/y.npy'
